name: Continent Boundary for South America (SA)

on:
  schedule:
    - cron: '0 4 7 * *'  # Monthly on day 7 at 04:00 UTC
  workflow_dispatch:

jobs:
  boundary-continent-sa:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: sa
      entity_name: South America
      entity_type: continent
      osm_query: 'a[place=continent]["name:en"="South America"]'
      remote_path: /osm/boundaries/continents/sa
      remote_version: '1'
      tags: |
        boundary
        continent
        south-america
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
