name: Country Boundary for Cocos (CC)

on:
  schedule:
    - cron: '10 2 5 * *'  # Monthly on day 5 at 02:10 UTC
  workflow_dispatch:

jobs:
  boundary-country-cc:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: cc
      entity_name: Cocos
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="CC"]'
      remote_path: /osm/boundaries/countries/cc
      remote_version: '1'
      tags: |
        boundary
        country
        cocos
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
