name: Country Boundary for Congo (CG)

on:
  schedule:
    - cron: '25 2 5 * *'  # Monthly on day 5 at 02:25 UTC
  workflow_dispatch:

jobs:
  boundary-country-cg:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: cg
      entity_name: Congo
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="CG"]'
      remote_path: /osm/boundaries/countries/cg
      remote_version: '1'
      tags: |
        boundary
        country
        congo
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
