name: Country Boundary for Chile (CL)

on:
  schedule:
    - cron: '0 2 6 * *'  # Monthly on day 6 at 02:00 UTC
  workflow_dispatch:

jobs:
  boundary-country-cl:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: cl
      entity_name: Chile
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="CL"]'
      remote_path: /osm/boundaries/countries/cl
      remote_version: '1'
      tags: |
        boundary
        country
        chile
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
