name: Country Boundary for Curaçao (CW)

on:
  schedule:
    - cron: '35 2 6 * *'  # Monthly on day 6 at 02:35 UTC
  workflow_dispatch:

jobs:
  boundary-country-cw:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: cw
      entity_name: Curaçao
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="CW"]'
      remote_path: /osm/boundaries/countries/cw
      remote_version: '1'
      tags: |
        boundary
        country
        curaçao
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
