name: Country Boundary for Iceland (IS)

on:
  schedule:
    - cron: '0 2 13 * *'  # Monthly on day 13 at 02:00 UTC
  workflow_dispatch:

jobs:
  boundary-country-is:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: is
      entity_name: Iceland
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="IS"]'
      remote_path: /osm/boundaries/countries/is
      remote_version: '1'
      tags: |
        boundary
        country
        iceland
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
