name: Country Boundary for Jersey (JE)

on:
  schedule:
    - cron: '10 2 13 * *'  # Monthly on day 13 at 02:10 UTC
  workflow_dispatch:

jobs:
  boundary-country-je:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: je
      entity_name: Jersey
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="JE"]'
      remote_path: /osm/boundaries/countries/je
      remote_version: '1'
      tags: |
        boundary
        country
        jersey
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
