name: Country Boundary for Kyrgyzstan (KG)

on:
  schedule:
    - cron: '35 2 13 * *'  # Monthly on day 13 at 02:35 UTC
  workflow_dispatch:

jobs:
  boundary-country-kg:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: kg
      entity_name: Kyrgyzstan
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="KG"]'
      remote_path: /osm/boundaries/countries/kg
      remote_version: '1'
      tags: |
        boundary
        country
        kyrgyzstan
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
