name: Country Boundary for Comoros (KM)

on:
  schedule:
    - cron: '5 2 14 * *'  # Monthly on day 14 at 02:05 UTC
  workflow_dispatch:

jobs:
  boundary-country-km:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: km
      entity_name: Comoros
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="KM"]'
      remote_path: /osm/boundaries/countries/km
      remote_version: '1'
      tags: |
        boundary
        country
        comoros
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
