name: Country Boundary for South Korea (KR)

on:
  schedule:
    - cron: '20 2 14 * *'  # Monthly on day 14 at 02:20 UTC
  workflow_dispatch:

jobs:
  boundary-country-kr:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: kr
      entity_name: South Korea
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="KR"]'
      remote_path: /osm/boundaries/countries/kr
      remote_version: '1'
      tags: |
        boundary
        country
        south-korea
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
