name: Country Boundary for Lao People's Democratic Republic (LA)

on:
  schedule:
    - cron: '40 2 14 * *'  # Monthly on day 14 at 02:40 UTC
  workflow_dispatch:

jobs:
  boundary-country-la:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: la
      entity_name: Lao People's Democratic Republic
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="LA"]'
      remote_path: /osm/boundaries/countries/la
      remote_version: '1'
      tags: |
        boundary
        country
        lao-people's-democratic-republic
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
