name: Country Boundary for Lebanon (LB)

on:
  schedule:
    - cron: '0 2 15 * *'  # Monthly on day 15 at 02:00 UTC
  workflow_dispatch:

jobs:
  boundary-country-lb:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: lb
      entity_name: Lebanon
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="LB"]'
      remote_path: /osm/boundaries/countries/lb
      remote_version: '1'
      tags: |
        boundary
        country
        lebanon
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
