name: Country Boundary for Liechtenstein (LI)

on:
  schedule:
    - cron: '10 2 15 * *'  # Monthly on day 15 at 02:10 UTC
  workflow_dispatch:

jobs:
  boundary-country-li:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: li
      entity_name: Liechtenstein
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="LI"]'
      remote_path: /osm/boundaries/countries/li
      remote_version: '1'
      tags: |
        boundary
        country
        liechtenstein
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
