name: Country Boundary for Lithuania (LT)

on:
  schedule:
    - cron: '30 2 15 * *'  # Monthly on day 15 at 02:30 UTC
  workflow_dispatch:

jobs:
  boundary-country-lt:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: lt
      entity_name: Lithuania
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="LT"]'
      remote_path: /osm/boundaries/countries/lt
      remote_version: '1'
      tags: |
        boundary
        country
        lithuania
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
