name: Country Boundary for Libya (LY)

on:
  schedule:
    - cron: '0 2 16 * *'  # Monthly on day 16 at 02:00 UTC
  workflow_dispatch:

jobs:
  boundary-country-ly:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: ly
      entity_name: Libya
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="LY"]'
      remote_path: /osm/boundaries/countries/ly
      remote_version: '1'
      tags: |
        boundary
        country
        libya
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
