name: Country Boundary for Marshall Islands (MH)

on:
  schedule:
    - cron: '35 2 16 * *'  # Monthly on day 16 at 02:35 UTC
  workflow_dispatch:

jobs:
  boundary-country-mh:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: mh
      entity_name: Marshall Islands
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="MH"]'
      remote_path: /osm/boundaries/countries/mh
      remote_version: '1'
      tags: |
        boundary
        country
        marshall-islands
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
