name: Country Boundary for Macao (MO)

on:
  schedule:
    - cron: '15 2 17 * *'  # Monthly on day 17 at 02:15 UTC
  workflow_dispatch:

jobs:
  boundary-country-mo:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: mo
      entity_name: Macao
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="MO"]'
      remote_path: /osm/boundaries/countries/mo
      remote_version: '1'
      tags: |
        boundary
        country
        macao
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
