name: Country Boundary for Martinique (MQ)

on:
  schedule:
    - cron: '25 2 17 * *'  # Monthly on day 17 at 02:25 UTC
  workflow_dispatch:

jobs:
  boundary-country-mq:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: mq
      entity_name: Martinique
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="MQ"]'
      remote_path: /osm/boundaries/countries/mq
      remote_version: '1'
      tags: |
        boundary
        country
        martinique
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
