name: Country Boundary for Namibia (NA)

on:
  schedule:
    - cron: '30 2 18 * *'  # Monthly on day 18 at 02:30 UTC
  workflow_dispatch:

jobs:
  boundary-country-na:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: na
      entity_name: Namibia
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="NA"]'
      remote_path: /osm/boundaries/countries/na
      remote_version: '1'
      tags: |
        boundary
        country
        namibia
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
