name: Country Boundary for Netherlands (NL)

on:
  schedule:
    - cron: '15 2 19 * *'  # Monthly on day 19 at 02:15 UTC
  workflow_dispatch:

jobs:
  boundary-country-nl:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: nl
      entity_name: Netherlands
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="NL"]'
      remote_path: /osm/boundaries/countries/nl
      remote_version: '1'
      tags: |
        boundary
        country
        netherlands
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
