name: Country Boundary for Peru (PE)

on:
  schedule:
    - cron: '10 2 20 * *'  # Monthly on day 20 at 02:10 UTC
  workflow_dispatch:

jobs:
  boundary-country-pe:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: pe
      entity_name: Peru
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="PE"]'
      remote_path: /osm/boundaries/countries/pe
      remote_version: '1'
      tags: |
        boundary
        country
        peru
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
