name: Country Boundary for French Polynesia (PF)

on:
  schedule:
    - cron: '15 2 20 * *'  # Monthly on day 20 at 02:15 UTC
  workflow_dispatch:

jobs:
  boundary-country-pf:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: pf
      entity_name: French Polynesia
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="PF"]'
      remote_path: /osm/boundaries/countries/pf
      remote_version: '1'
      tags: |
        boundary
        country
        french-polynesia
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
