name: Country Boundary for Poland (PL)

on:
  schedule:
    - cron: '35 2 20 * *'  # Monthly on day 20 at 02:35 UTC
  workflow_dispatch:

jobs:
  boundary-country-pl:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: pl
      entity_name: Poland
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="PL"]'
      remote_path: /osm/boundaries/countries/pl
      remote_version: '1'
      tags: |
        boundary
        country
        poland
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
