name: Country Boundary for Palestine (PS)

on:
  schedule:
    - cron: '10 2 21 * *'  # Monthly on day 21 at 02:10 UTC
  workflow_dispatch:

jobs:
  boundary-country-ps:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: ps
      entity_name: Palestine
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="PS"]'
      remote_path: /osm/boundaries/countries/ps
      remote_version: '1'
      tags: |
        boundary
        country
        palestine
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
