name: Country Boundary for Portugal (PT)

on:
  schedule:
    - cron: '15 2 21 * *'  # Monthly on day 21 at 02:15 UTC
  workflow_dispatch:

jobs:
  boundary-country-pt:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: pt
      entity_name: Portugal
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="PT"]'
      remote_path: /osm/boundaries/countries/pt
      remote_version: '1'
      tags: |
        boundary
        country
        portugal
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
