name: Country Boundary for Réunion (RE)

on:
  schedule:
    - cron: '35 2 21 * *'  # Monthly on day 21 at 02:35 UTC
  workflow_dispatch:

jobs:
  boundary-country-re:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: re
      entity_name: Réunion
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="RE"]'
      remote_path: /osm/boundaries/countries/re
      remote_version: '1'
      tags: |
        boundary
        country
        réunion
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
