name: Country Boundary for Solomon Islands (SB)

on:
  schedule:
    - cron: '20 2 22 * *'  # Monthly on day 22 at 02:20 UTC
  workflow_dispatch:

jobs:
  boundary-country-sb:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: sb
      entity_name: Solomon Islands
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="SB"]'
      remote_path: /osm/boundaries/countries/sb
      remote_version: '1'
      tags: |
        boundary
        country
        solomon-islands
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
