name: Country Boundary for Sudan (SD)

on:
  schedule:
    - cron: '30 2 22 * *'  # Monthly on day 22 at 02:30 UTC
  workflow_dispatch:

jobs:
  boundary-country-sd:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: sd
      entity_name: Sudan
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="SD"]'
      remote_path: /osm/boundaries/countries/sd
      remote_version: '1'
      tags: |
        boundary
        country
        sudan
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
