name: Country Boundary for Sweden (SE)

on:
  schedule:
    - cron: '35 2 22 * *'  # Monthly on day 22 at 02:35 UTC
  workflow_dispatch:

jobs:
  boundary-country-se:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: se
      entity_name: Sweden
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="SE"]'
      remote_path: /osm/boundaries/countries/se
      remote_version: '1'
      tags: |
        boundary
        country
        sweden
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
