name: Country Boundary for Svalbard and Jan Mayen (SJ)

on:
  schedule:
    - cron: '10 2 23 * *'  # Monthly on day 23 at 02:10 UTC
  workflow_dispatch:

jobs:
  boundary-country-sj:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: sj
      entity_name: Svalbard and Jan Mayen
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="SJ"]'
      remote_path: /osm/boundaries/countries/sj
      remote_version: '1'
      tags: |
        boundary
        country
        svalbard-and-jan-mayen
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
