name: Country Boundary for El Salvador (SV)

on:
  schedule:
    - cron: '10 2 24 * *'  # Monthly on day 24 at 02:10 UTC
  workflow_dispatch:

jobs:
  boundary-country-sv:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: sv
      entity_name: El Salvador
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="SV"]'
      remote_path: /osm/boundaries/countries/sv
      remote_version: '1'
      tags: |
        boundary
        country
        el-salvador
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
