name: Country Boundary for Sint Maarten (SX)

on:
  schedule:
    - cron: '15 2 24 * *'  # Monthly on day 24 at 02:15 UTC
  workflow_dispatch:

jobs:
  boundary-country-sx:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: sx
      entity_name: Sint Maarten
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="SX"]'
      remote_path: /osm/boundaries/countries/sx
      remote_version: '1'
      tags: |
        boundary
        country
        sint-maarten
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
