name: Country Boundary for Chad (TD)

on:
  schedule:
    - cron: '35 2 24 * *'  # Monthly on day 24 at 02:35 UTC
  workflow_dispatch:

jobs:
  boundary-country-td:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: td
      entity_name: Chad
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="TD"]'
      remote_path: /osm/boundaries/countries/td
      remote_version: '1'
      tags: |
        boundary
        country
        chad
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
