name: Country Boundary for Uganda (UG)

on:
  schedule:
    - cron: '25 2 26 * *'  # Monthly on day 26 at 02:25 UTC
  workflow_dispatch:

jobs:
  boundary-country-ug:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: ug
      entity_name: Uganda
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="UG"]'
      remote_path: /osm/boundaries/countries/ug
      remote_version: '1'
      tags: |
        boundary
        country
        uganda
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
