name: Country Boundary for Holy See (VA)

on:
  schedule:
    - cron: '5 2 27 * *'  # Monthly on day 27 at 02:05 UTC
  workflow_dispatch:

jobs:
  boundary-country-va:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: va
      entity_name: Holy See
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="VA"]'
      remote_path: /osm/boundaries/countries/va
      remote_version: '1'
      tags: |
        boundary
        country
        holy-see
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
