name: Country Boundary for South Africa (ZA)

on:
  schedule:
    - cron: '15 2 28 * *'  # Monthly on day 28 at 02:15 UTC
  workflow_dispatch:

jobs:
  boundary-country-za:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: za
      entity_name: South Africa
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="ZA"]'
      remote_path: /osm/boundaries/countries/za
      remote_version: '1'
      tags: |
        boundary
        country
        south-africa
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
