name: Country Boundary for Zimbabwe (ZW)

on:
  schedule:
    - cron: '25 2 28 * *'  # Monthly on day 28 at 02:25 UTC
  workflow_dispatch:

jobs:
  boundary-country-zw:
    uses: ./.github/workflows/boundaries/reusable-boundaries.yaml
    with:
      entity_code: zw
      entity_name: Zimbabwe
      entity_type: country
      osm_query: 'a["ISO3166-1:alpha2"="ZW"]'
      remote_path: /osm/boundaries/countries/zw
      remote_version: '1'
      tags: |
        boundary
        country
        zimbabwe
        geojson
        openstreetmap
        public
    secrets:
      RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
